### ISSUE TITLE
Getting error when using lambda....

### ISSUE THREAD

**Issue by vadimuchitel** [devopsfaith/krakend-lambda#5]
When I am using krakend lambda function module, I am getting this error message:
{
    "errorMessage": "'str' object has no attribute 'get'",
    "errorType": "AttributeError",
    "stackTrace": [
        "  File \"/var/runtime/bootstrap.py\", line 128, in handle_event_request\n    lambda_context = create_lambda_context(client_context_json, cognito_identity_json, epoch_deadline_time_in_ms,\n",
        "  File \"/var/runtime/bootstrap.py\", line 171, in create_lambda_context\n    return LambdaContext(invoke_id, client_context, cognito_identity, epoch_deadline_time_in_ms,\n",
        "  File \"/var/runtime/bootstrap.py\", line 256, in __init__\n    self.client_context.client = make_obj_from_dict(Client, self.client_context.client)\n",
        "  File \"/var/runtime/bootstrap.py\", line 232, in make_obj_from_dict\n    set_obj_from_dict(obj, _dict)\n",
        "  File \"/var/runtime/bootstrap.py\", line 240, in set_obj_from_dict\n    setattr(obj, field, _dict.get(field, None))\n"
    ]
}
Commenting out this line (clientContext): https://github.com/devopsfaith/krakend-lambda/blob/cce9724ca461a2f35f8e095931e07bf5aa325dc4/backend.go#L64
resolves the issue.

**Comment by kpacha** [comment]
I didn't think about closing this after the PR (https://github.com/devopsfaith/krakend-lambda/pull/6)...

thanks for the heads up
